S = {...
	'adasd4_ad.txt';...
	'adasd4_sd4.txt';...
	'adau9_ad.txt';...
	'adau9_au9.txt';...
	'nlabe_abe.txt';...
	'nlabe_nl.txt';...
    'nlabn_abn.txt';...
    'nlabn_nl.txt';...
    'nladc_adc.txt';...
    'nladc_nl.txt';...
    'nladd_add.txt';...
    'nladd_nl.txt';...
    'nlasd_asd.txt';...
    'nlasd_nl.txt';...
    'nlauc_auc.txt';...
    'nlauc_nl.txt';...
};
M = size(S,1);
Sp = 'C:\BDxDx\kiddiscrim2\';

for i = 1:16
	
	S1 = [Sp, S{i}];
	nl = load(S1);
	nl = sort(nl,1);
	
	N = size(nl,1);
	a = sum(nl(:,2) < .95);
	b = sum(nl(:,2) >= .99);
	g = a:(N-b);
	fprintf(1,'%8.3f %8.3f\n', nl(a,:));
	fprintf(1,'%8.3f %8.3f\n', nl(N-b,:));
	[a,k] = min(abs(nl(:,2)-.99));
	fprintf(1,'%8.3f %8d %8d\n',a,k,N);
	
	plot(nl(g,1),nl(g,2));
	title(S(i));
	('Probability');
	xlabel('Discriminant Score');
	pause
end
